default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files # prevents adding large files, above 500kB
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-merge-conflict
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: package.lock.json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # pick latest stable
    hooks:
      - id: prettier
        additional_dependencies: [prettier@^3.0.0]
        files: \.(js|ts|vue|json|css|scss|md)$
        args: ["--write"]
        always_run: true
        pass_filenames: true
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.46.0 # pick latest stable
    hooks:
      - id: eslint
        additional_dependencies: [eslint@^8.0.0, eslint-plugin-vue@^9.0.0]
        files: \.(js|ts|vue)$
        args: ["--fix"]
